language: c
sudo: false

branches:
  only:
    - master
    - rv-toolkit-test

cache: apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-5
    - gcc-6

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    compiler: gcc-4.8
  - os: linux
    compiler: gcc-5
  - os: linux
    compiler: gcc-6
  - os: osx
    compiler: clang
    osx_image: xcode6.2
  - os: osx
    compiler: clang
    osx_image: xcode7.3
  - os: osx
    compiler: clang
    osx_image: xcode8
  - os: osx
    env: INSTALL=gcc48
    compiler: gcc-4.8
  - os: osx
    env: INSTALL=gcc
    compiler: gcc-6
    osx_image: xcode8
  - os: linux
    env: TOOLKIT=true

before_install:
  - if [ "$TRAVIS_OS_NAME" == osx -a "$INSTALL" ] ; then brew install $INSTALL || true ; fi

script: |
  if [[ $TOOLKIT == true ]]; then
    bash <(curl -s https://runtimeverification.com/toolkit/docker/bash) nightly-2018-08-31
  else 
    make
    make test
  fi
